# -*- coding: utf-8 -*-
"""BI ASSIGNMENT 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQ7gbBASvi-bYcKOK0ZDhUg_8W4OgDVf
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
import numpy as np

# Load the data from the Excel file
file_path = 'Sentiment Analysis.xlsx'  # Update this path if necessary
df = pd.read_excel(file_path, sheet_name='Sheet1')

# Display the first few rows of the DataFrame
df.head()

# Convert 'Date' and 'Time' columns to datetime
df['DateTime'] = pd.to_datetime(df['Date'].astype(str) + ' ' + df['Time'].astype(str))

# Extract day of the week and hour of the day
df['DayOfWeek'] = df['DateTime'].dt.day_name()
df['HourOfDay'] = df['DateTime'].dt.hour

# Group by DayOfWeek and Sentiment
day_sentiment = df.groupby(['DayOfWeek', 'Sentiment']).size().unstack().fillna(0)

# Group by HourOfDay and Sentiment
hour_sentiment = df.groupby(['HourOfDay', 'Sentiment']).size().unstack().fillna(0)

# Plotting
plt.figure(figsize=(14, 6))

# Sentiment by Day of Week
plt.subplot(1, 2, 1)
day_sentiment.plot(kind='bar', stacked=True, ax=plt.gca())
plt.title('Sentiment by Day of Week')
plt.xlabel('Day of Week')
plt.ylabel('Count')

# Sentiment by Hour of Day
plt.subplot(1, 2, 2)
hour_sentiment.plot(kind='bar', stacked=True, ax=plt.gca())
plt.title('Sentiment by Hour of Day')
plt.xlabel('Hour of Day')
plt.ylabel('Count')

plt.tight_layout()
plt.show()

# Combine all text from positive and negative posts
positive_text = ' '.join(df[df['Sentiment'] == 'Positive']['Text'])
negative_text = ' '.join(df[df['Sentiment'] == 'Negative']['Text'])

# Generate word clouds
positive_wordcloud = WordCloud(width=800, height=400, background_color='white').generate(positive_text)
negative_wordcloud = WordCloud(width=800, height=400, background_color='black').generate(negative_text)

# Plotting
plt.figure(figsize=(14, 6))

# Positive Word Cloud
plt.subplot(1, 2, 1)
plt.imshow(positive_wordcloud, interpolation='bilinear')
plt.title('Positive Posts Word Cloud')
plt.axis('off')

# Negative Word Cloud
plt.subplot(1, 2, 2)
plt.imshow(negative_wordcloud, interpolation='bilinear')
plt.title('Negative Posts Word Cloud')
plt.axis('off')

plt.tight_layout()
plt.show()

# Plotting
plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x='Sentiment', y='Upvotes', palette='viridis', order=['Positive', 'Neutral', 'Negative'])
plt.title('Distribution of Upvotes by Sentiment')
plt.xlabel('Sentiment')
plt.ylabel('Upvotes')
plt.tight_layout()
plt.show()

# Calculate the average Upvotes for each sentiment
avg_upvotes_by_sentiment = df.groupby('Sentiment')['Upvotes'].mean().reset_index()

# Sort the data for better visualization
avg_upvotes_by_sentiment = avg_upvotes_by_sentiment.sort_values(by='Upvotes', ascending=False)

# Define the threshold for the most populated region (e.g., top 25%)
threshold = avg_upvotes_by_sentiment['Upvotes'].max() * 0.75

# Plotting
plt.figure(figsize=(8, 6))
bars = plt.bar(avg_upvotes_by_sentiment['Sentiment'], avg_upvotes_by_sentiment['Upvotes'], color='lightblue')

# Highlight the most populated regions in red
for bar in bars:
    height = bar.get_height()
    if height >= threshold:
        bar.set_color('red')

# Add labels and title
plt.title('Average Upvotes by Sentiment (Most Populated Regions in Red)')
plt.xlabel('Sentiment')
plt.ylabel('Average Upvotes')
plt.tight_layout()
plt.show()